### ISSUE TITLE
Clanchat bugs

### ISSUE THREAD

**Issue by zifnab06** [NerdNu/NerdBugs#117]
Related to channel deletion:
1. If everyone leaves a clanchat, the channel should be deleted, but is not. (IE, start of rev I decide to register pico/seneca/argoth/port80/endor, then leave all of them. Those channels are still registered on the server, however no one can join them) From what i can tell there is no support at all for deleting channels. 
2. Owners can leave their clanchat, leaving the chat "ownerless". I put that in quotes because you are still the owner in the database, so if you rejoin you are once again owner. _cc_leave_channel($channel) should check to see if you are an owner before allowing you to leave. 

(If the owner is the last person in the chat, and leaves, it should be deleted. Otherwise, the owner can't leave, and must promote someone to owner before leaving)

Other misc issues:
1. Typing /clanchat randomwordshere prints "Command Not Found". Should it instead print the same thing that /clanchat prints out: ie, the help? .
2. Typing "/c #channel" should print a message stating "You are not in #channel", instead of letting you 'switch' to that channel. (/c still checks to see if you are a member before allowing you to send text to said channel anyways, so this is probably not needed)
3. Text for /cm is wrong in /clanchat. Should be updated to: "/cm [#<channel>]- Lists all members in your default channel. If a channel is given, lists members in that channel."

I've done some work on clanchat already (/cm and /clanchat owner), and would be interested in fixing these, assuming that they are actually issues.

**Comment by LadyCailin** [comment]
Well, if you're volunteering...

1a. I'm ok with doing something different here, I just hadn't, since this is a relative edge case.
2a. There's some inconsistencies, yes

1b. Sure. Should be easy enough to fix.
2b. A simple check could be added, sure
3b. I'm ok with this getting fixed

Do you care to claim ownership for this bug? If so, let me know, and I'll hold off on doing it myself (thanks!)

**Comment by zifnab06** [comment]
I will. I probably won't get a chance to take a look at it till the weekend, but gladly!

**Comment by zifnab06** [comment]
Guess I should let you know what's changed in this verison:

Clanchat owner can no longer leave the channel, unless they are the last player in said channel. If they are the only person in the channel and they leave, the channel is deleted and can be re-registered by anyone, the same way as a non-created channel.

/clanchat <invalid command> will now print out a help message. 

/c #channel and /cm #channel will print an error message if the player is not in said channel. (/cm was implemented due to an upcoming event on S. If the channel name gets out, it kind of ruins the event, as people can see who is involved)

Thanks!

**Comment by ghost** [comment]
I don't really understand why /cm #channel is being removed if you're not in that channel. Currently, it's an incredibly convenient feature on P, which I use all the time, and I see no reason to get rid of it. It's especially true for most people, who are in multiple clanchats, but would like to check the status of the ones they aren't currently in without hopping all over the place. 

If it's really that much of a problem on S, then perhaps A) it should be killed on S but not on P (I know that this is probably a pretty stupidly unlikely solution) or B) you can just not give out the channel names of channels you want to be secret. For the spleef event we had on S recently, the problem we had was not that people found out due to clanchat.

**Comment by zifnab06** [comment]
Thinking about it, @Diznatch52  has a very good point. I just put the code there as I had added it elsewhere (to fix /c), and because, at the time, I was thinking on S you really wouldn't want to be able to see who is working together, assuming they are doing so covertly and weren't already a part of a clan. 

Instead, I propose adding some sort of flags system. Possibly, for now, "secret" and "public". Public channels could be joined by anyone without an invite (This has been requested multiple times by various users), and "secret" channels would lose the /cm #channelname if you aren't in the channel. 

This would also require a database change, which I am fairly comfortable doing at this point in time. An added field for flags, possibly just a simple string (s for secret, p for private, blank for neither, etc) added to clanchat.channels.<channel>.flags

(/clanchat flags <channel> <flag> <ON/OFF>)

I'd need @LadyCailin's input before I actually try to make that change. 

(On a side note: Sorry for not having time to finish the rest of this yet. I'm currently doing summer classes, and they have been way too much work so far. I'm only taking 1 course next session, starts July 1st, so that should give me a little more time to finish projects like this)

**Comment by LadyCailin** [comment]
I'm ok with that, though with the database change, you'll need to add a default if the channel doesn't have that data yet. Like you said, several people have requested that feature.
