### ISSUE TITLE
Re-implement Villagers On S.

### ISSUE THREAD

**Issue by draykhar** [NerdNu/NerdBugs#119]
We haven't had Villagers on Survival since Rev 17, and for good reason: They're easily exploitable. A few people running a reed/villager farm were able to inundate the server with full diamond loadouts. Their trades are terribly unfair. 

On the other hand, villagers and trading with them are a significant part of the minecraft experience. Without them, emeralds are useless, villages are abandoned, and commerce is suffering.

I'd like for this to be remedied. 

The plugin that I found that I feel would best work for the job is Rebalance Villagers (http://dev.bukkit.org/bukkit-mods/rebalance-villagers/ ). It would disable the vanilla system of trade/offer removal that was exploitable in the past, and allow us to configure which trades are available, and what the prices for them are.

**Comment by Tharine** [comment]
Commenting just to clarify that i've signed off on the idea alongside draykhar, and in the absence of cmchappell's commentary, I know he was keen to see how this sort of thing would pan out as well.

Additionally, i've brought this plugin (alongside one other) to the tech admin's attention several times in asking about potential compatibility issues or how difficult this might be to implement, to no response. Could we get a proper assessment made of this plugin, please?

**Comment by LadyCailin** [comment]
Ok, I looked at the plugin, and it looks safe, so I wouldn't have any security concerns when installing it. You guys would be in charge of giving us the configuration file, and we would be in charge of keeping the plugin itself updated. I'm a bit curious if they have taken the best approach in coding the plugin, however, if it works, it works. In the future, I may take a crack at it with CH, since offhand I can think of a better approach, but unless they don't update or something later, it should be fine as is.

Are we still interested?

**Comment by draykhar** [comment]
Configs have been written and handed off to you, ready to go with it for the next rev.

**Comment by totemo** [comment]
I note that the new rev has arrived and we are indeed running this plugin.  Closing.
