### ISSUE TITLE
Modreqs, homes, and warps should record heading

### ISSUE THREAD

**Issue by GMMan** [NerdNu/NerdBugs#121]
Particularly, modreqs, because it could be confusing for moderators who don't know what exactly to look for. Please see C modreq 1036 and 1037 .

**Comment by LadyCailin** [comment]
This is straightforward for homes and warps, since those are CH, but doing it for modreq would be a task for @Deaygo.

**Comment by zifnab06** [comment]
Modreqs now record headings, code added with this commit: https://github.com/NerdNu/ModReq/commit/4783bd204a8b83f05224873153b6bccb84354f7a

Edit - won't be available until the 1.6.2 update (as the package now builds for 1.6.2)

**Comment by LadyCailin** [comment]
I believe that this should be fixed in CH now as well, as most things were standardized to use location arrays. It may require re-setting the homes or warp, but after that, should work. ModReq has also since been updated, so I'm closing this bug. Let me know if there are any other places that aren't fixed!
