### ISSUE TITLE
Give defaults access to /seen on S

### ISSUE THREAD

**Issue by FourDown** [NerdNu/NerdBugs#122]
Would be useful for us.

Can't seen any downsides.

**Comment by LadyCailin** [comment]
Yeah, this wasn't intentional at all.

**Comment by zifnab06** [comment]
It is also unavailable on P, not sure if that was intentional or not.

**Comment by gsand** [comment]
```
*:/seen $player $ = >>>
if(!phas_played($player)){
    die(colorize('&cPlease use the exact player name of the person.'))
}
else{
msg(sconcat($player, 'last played on', simple_date('EEE, d MMM at hh:mm aaa, z', plast_played($player), 'GMT')))
}
<<<
```

**Comment by totemo** [comment]
Rolled out a case-insensitive /seen under: https://github.com/NerdNu/NerdBugs/issues/90

I'd like to confirm with the server admins before I give default access to these commands, since it's a really a policy issue now.  The technical fix is simply to remove the permission check.  There is the potential for players to take matters into their own hands if they think a claim is "abandoned", so I'd like the server admins to state their position.

**Comment by tompreuss** [comment]
In addition to the issue you raise regarding taking things into their own hands, there are also other subtle privacy and harassment issues that could potentially be involved.  While most requests made by players to moderators to run /seen on a player are completed without any issue, we'd like to retain the ability to be able to deny such a request if necessary depending on the circumstances.

As such, the padmins want the /seen command to remain moderator only.

**Comment by draykhar** [comment]
Tharine and I would like to implement this on Survival. We've reached the conclusion that if harassment via this becomes and issue, we'll deal with that as we do all other harassment situations. Warn/Ban.

Thanks!

**Comment by totemo** [comment]
Ok, I shall make it so.

**Comment by totemo** [comment]
Accessible to defaults on Survival and to staff only on Creative and PVE. If a Creative admin wants this command available on that server, ask a tech admin to grant defaults the nerdch.level.seen permission.
