### ISSUE TITLE
Remove falsified plugins list for players on Survival

### ISSUE THREAD

**Issue by Tharine** [NerdNu/NerdBugs#132]
I believe all three Survival admins made it pretty clear that we would like to have the falsified plugins list removed and replaced with the actual one in the original ticket for the plugins list issue: https://github.com/NerdNu/NerdBugs/issues/115

For players, the plugins list (typing both /pl and /plugins) returns this list: http://i.imgur.com/WiPgDmT.png which not only hides some of our current plugins, it actually falsely states that we use plugins such as MCCondom and PermissionsEx. Here's what shows when I run either of those commands: http://i.imgur.com/MCM6JXQ.png. I'm unsure whether an incorrect list was accidentally put in when the commands were re-enabled (we haven't used some of those plugins in a /long/ time), but we would like this remedied as soon as possible either way - thanks!

**Comment by nopresnik** [comment]
Just a quick chip in to say that this is the case across all three servers (C, P, S)

**Comment by totemo** [comment]
I'm at fault for setting /pl up to work the same on all three servers.  It gives the correct result for an admin and gives a false list for defaults.  To me that seems entirely reasonable.  Apart from letting players know that they can use LWC, I don't know why a default player would even care unless it's to attempt to circumvent the rules without detection.

I would have thought the definitive word was already said by a head admin (https://github.com/NerdNu/NerdBugs/issues/115#issuecomment-19348346).  I interpret those remarks to mean that a faked plugin list is ok.

I'm curious as to why you think it is important for players to know the actual plugins in use.

**Comment by barneygale** [comment]
> I'm curious as to why you think it is important for players to know the actual plugins in use.

This is just my opinion, but the reason is two-fold:
1. There's no compelling technical or security-based reason not to.
   1. There's no evidence griefing clients check the plugin list anymore. 
   2. Even if they did, it can be solved by switching aliases around a little (`/plugins` says "Please check /listplugins", `/listplugins` shows real plugin list)
   3. Plugin list is public info anyway, from update progress spreadsheets and whatnot
2. MCPublic has a tradition of publishing information for the sake of openness. You make server logs available where other servers don't (are they fixed now?). IRC is (was?) publicly logged. You used to also publish the moderation log for the subreddit, which I believe took some significant code work, purely for the sake of openness.

The plugin list falsification was really only set up to combat nodus, but as I say there are simpler ways to do that, and I don't even think nodus exists anymore.

Also, I feel like I'm restating points that haven't properly been responded to in the head admin post you linked. It presents a false dilemma: that we either fake the plugin list, or hacked clients will be able to detect we're running NCP. This isn't the case, as hacked clients can be easily fooled by, as I mentioned, simply changing the command name or even the formatting. The rest of the argument is essentially "there's little benefit", which strikes me as totally out-of-synch with the ethos of mcpublic under prior heads, where things like this and public logs would be approved in the name of openness, rather than receiving this "war against hackers" tripe.

And the reasoning that "ordinary players don't want this" (paraphrasing) is never substantiated. I would have thought the survival admins would have a closer ear to their playerbase than a head admin. Whatever.

**Comment by GMMan** [comment]
Ahem, ordinary player here. I have been trying to make a build of NerdBukkit with plugins for the purpose of loading old C maps and simulating the environment as possible. Without a proper plugin list I had to resort to compiling all NerdNu plugins and guesstimating what other plugins are used. My sentiments are [here](https://nerd.nu/forum/index.php?/topic/513-two-new-commands-for-players/#entry3760).

**Comment by nopresnik** [comment]
Well, I can see the point from both sides.

`<smartass>`
Just sayin' if you really want to hide plugins, do it correctly. You must have forgotten to put [$] on the end of the /pl alias or something. You can still see real plugins if you type any argument after /pl eg. `/pl ajhdgf` So get em' quick @GMMan
`</smartass>`

**Comment by GMMan** [comment]
@nopresnik Thanks for that. Ran and committed to local console log.

Hmm... MCCondom. Whatever that is.
Edit: Found what MCCondom is. Funny name. No longer relevant.

**Comment by totemo** [comment]
@GMMan: On the forums you said:

> I just noticed the new code for /pl. So now we can't be honest about what plugins we used? If the output isn't going to truthfully reflect what's actually running, why have the command in the first place?

As far as I'm aware, not fully disclosing the plugin list has been the situation for some considerable time, for the purposes of preventing hacked clients from going into a harder to detect mode.  A few weeks ago, I was scolded by a head admin for revealing that we don't currently run NCP on PvE.  There are thus legitimate reasons why we might want to secretive about it.  The only thing that keeps some players honest is the chance of detection.  Numerous times, players have said that to me about xraying.

Why have the command in the first place? People who run it as their first action on the server are often up to no good and it's useful to know who they are.

@nopresnik: Regardless of whether you agree with the practice of hiding the plugin list, I'm appalled that you would use your technical knowledge against the professed interests of the server by publicly disclosing a vulnerability first, albeit a small one.

Now I feel a little bit like the meat in the sandwich here, because whatever I do about this, someone is going to be unhappy.  However, I certainly won't be going against the wishes of the head admins.

**Comment by nopresnik** [comment]
@totemo I can't see why there is such a large problem with allowing players to view plugins in-game. There are **many** [other ways to view the plugins](https://docs.google.com/spreadsheet/ccc?key=0Ah6wg6DGNNqwdFdocXdWSUdHSVlxOU81Q1BfZDIweGc#gid=2) (outside the game). It was brought up in the other bug report that it is safe to enable it again because there [aren't any hacked clients using the plugin list](https://github.com/NerdNu/NerdBugs/issues/115#issuecomment-19357968) as a way of going into a harder to detect mode.

So if we can view all the plugins nerd uses outside of the game and hacked clients aren't using `/pl` list for abuse, why can't we view them in the game?

@barneygale also had a great point. Nerd has always been publishing information about the servers since it started. So why do we have to change this openness all of a sudden and start locking things away that the public [can benefit of?](https://github.com/NerdNu/NerdBugs/issues/132#issuecomment-20882511)

**Edit:** I may also have circumvented a protection, but what's the point? As said above, there are many other ways to view the complete list.

**Comment by totemo** [comment]
> A few weeks ago, I was scolded by a head admin for revealing that we don't currently run NCP on PvE.
> However, I certainly won't be going against the wishes of the head admins.

**Comment by nopresnik** [comment]
Well, we'll wait for a head.

**Comment by LadyCailin** [comment]
The fake plugin list isn't all of a sudden. It has been in place for at least a year or so now.

**Comment by Deaygo** [comment]
This has been discussed and we will be updating the list to match the current plugins across the servers.  I am closing this now.
