### ISSUE TITLE
Moblimiter doesn't play well with worldguard

### ISSUE THREAD

**Issue by mattman00000** [NerdNu/NerdBugs#173]
Moblimiter fails to reduce refactory period for animals if they breed inside a region with mob spawning disabled (i.e. spawn) and a babby isn't formed.

**Comment by totemo** [comment]
Firstly, MobLimiter doesn't cancel the breeding; WorldGuard does.  The obligation is on WorldGuard to "do it right".

Secondly, it's not a problem that will affect many people.  Spawn is a tiny fraction of the map.  Most regions don't deny breeding.  

Thirdly, even if we were to regard this as important enough to fix, there doesn't appear to be a Bukkit API to restore the refractory period.  I would expect that if you were to raise this as a WorldGuard bug that they would close with "won't fix" because of that.  At it's root, the problem should probably be regarded as an issue in how Bukkit handles cancellation of that event.
