### ISSUE TITLE
General Metadata Associated with /Places - Add list of mayor names to /place command

### ISSUE THREAD

**Issue by 32ndFlava** [NerdNu/NerdBugs#178]
Would be very helpful to know who to contact in a specific town by using the /place command! Would reduce spamming of chat too.

**Comment by tompreuss** [comment]
`/place` is intended to be an easy way to point people to a location.  For finding information on who to contact in a town, we've always left that to `/region info` or town notice boards.  Additionally, since regions are managed by their owners, players/mayors are already in direct control of the listing of owners for a region, without needing any staff intervention.
