### ISSUE TITLE
Some Arrows Don't Despawn on S

### ISSUE THREAD

**Issue by roastnewt** [NerdNu/NerdBugs#186]
For some reason, there are arrows on Survival that never despawn.  They're from infinity bows, so they can't be picked up.

I don't know what causes some arrows to become immortal, but they're starting to build up, especially on the road.  Eventually that many entities could start to cause server lag.

Perhaps we could add "/rem arrows 1000000" or something to the mark2 scheduler, to run every so often?  I'm sure if it happened at 2am no one would notice the arrows disappearing.

**Comment by tompreuss** [comment]
See also [MC-31577](https://mojang.atlassian.net/browse/MC-31577).

**Comment by ethancedrik** [comment]
yep, it's not just us, I looked it up and there are posts on
MinecraftForums, etc, and that Mojira report

**Comment by totemo** [comment]
> Perhaps we could add "/rem arrows 1000000" or something to the mark2 scheduler, to run every so often?

Good idea.  I've scheduled it for a minute before each restart on S and P.  I think it has to happen during times when players are around or else the chunks would not be loaded.

**Comment by coolgamerovr90** [comment]
Maybe take a look at how much  lag would be noticeable when mark2 runs /rem arrows 1000000 more frequently, as the player count on the server is higher than it was last rev when this was implemented, and running a command like this might cause some lag.

Maybe it could be ran right before the server makes a backup of the map, so when people see "MAP IS SAVING, PREPARE FOR LAG" they will already be expecting it, and also the entity count for that map backup would be lower since all the arrows in the map would be gone

**Comment by roastnewt** [comment]
Fixed, closing
