### ISSUE TITLE
Some named mobs are culled when they are not supposed to be

### ISSUE THREAD

**Issue by tompreuss** [NerdNu/NerdBugs#197]
After the Easter 2014 event, where prizes included named spawn eggs, we've noticed that MobLimiter appears to cull some named animals.

[This change](https://github.com/NerdNu/MobLimiter/commit/110d9059ba8511d8e0a5f0d52039fc8fbf3c0962#diff-2299bd2bee934e14437d49378b355d6e) by @totemo was designed to prevent this the last time it was reported, and as far as my testing goes the `tameable.isTamed()` check works (horses/cats/dogs aren't culled, named or not) and the armor wearing checks works, but when I spawn six white sheep from spawn eggs all named "Easter Egg Hunt 2014" and leave and return, only two remain, so something appears to be at issue with the `living.getCustomName()` method.  And it's not just the spawn egg names, I tested with regular sheep named normally with name tags with the same result.

**Comment by totemo** [comment]
I believe there is an underlying vanilla, Bukkit or Spigot bug, Tom, as noted on [Line 221](https://github.com/NerdNu/MobLimiter/blob/master/src/nu/nerd/moblimiter/MobLimiter.java#L221).  I have a  vague recollection of dealing with an issue with one player's mysteriously disappearing cats.  Part of it was some unexpected behaviour in CommandHelper's handling of Location arrays, whereby my code to adjust the Y coordinate to prevent tamed mobs spawning in the floor did not work, [fixed in this patch](https://github.com/NerdNu/nerdCH/commit/2467db3c0eeb75b30c33df9feb4a67013b72f5e3).

**Comment by tompreuss** [comment]
I've done more testing and this was fixed [here](https://github.com/NerdNu/MobLimiter/pull/9)/[here](https://github.com/NerdNu/MobLimiter/commit/8d98fb0fd22a9ce8313cbee05576177fc56346aa).

Thank you @totemo and @slide23.
