### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by MeowTheCatMan** [NerdNu/NerdBugs#202]
I am currently stuck inside the survival world; My username is General_B00M and I would like to be set into the Creative world if possible, because vanilla disallows me to go into the hub and such like that.

**Comment by lowell** [comment]
You can connect to Creative by entering `/creative` in the in-game chat, provided chat is enabled in your multiplayer options.

Alternatively, you can connect to Creative by adding its address to the server list on the Multiplayer screen or by connecting directly to it (also from the multiplayer screen). The address is `c.nerd.nu`.

Also, if by 'stuck inside the survival world' you mean that you've ended up somewhere that you can't get out of due to permissions, type `/list` in chat and send a message to an in-game mod or admin.

**Comment by roastnewt** [comment]
@lowell he means he's on the survival server.  At the moment, Survival is running a chaos 1.8 vanilla server, with no plugins, so there's no way to change servers once you're there.

@MeowTheCatMan you can connect to lobby.nerd.nu to get back to the lobby.

**Comment by lowell** [comment]
Thanks, @roastnewt! Completely forgot that they're in between revs. :flushed:
