### ISSUE TITLE
Right-clicking fences on the hub causes them to disappear client-side

### ISSUE THREAD

**Issue by roastnewt** [NerdNu/NerdBugs#208]
Video:

https://youtu.be/jVp7t1E2SA4

**Comment by Denevien** [comment]
Roast, was looking through the issues, and I saw this one. I tried to replicate it on the current lobby, and I can't replicate the issue. Is this still happening on your end?

**Comment by roastnewt** [comment]
Nope, everything works as expected now.  So much has updated since then, we'll probably never know what caused it.

**Comment by redwallhp** [comment]
Fairly certain it was because we were running the protocol hack Spigot version back then on the lobby. So it didn't recognize the new non-oak fences as "real" blocks even though somebody had used them in the world. If players touched them, the event would cause them to disappear. I remember manually replacing them with oak fences at some point for this reason.

Unless I'm remembering the timeframe wrong...
