### ISSUE TITLE
Enable dispenser lava/water via SafeBuckets

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#27]
Fixing the issues that caused us to remove the ability for dispensers to output water/lava on S and P:

http://www.reddit.com/r/mcpublic/comments/y4jkx/a_change_to_your_dispensers/

"For these reasons we are trailing blocking of dispensers's ability to output water and lava when powered ( as per vanilla functionality )"

Dispensers still correctlly suck in water/lava if in front of it, just need to get the output side working.  The plan is to add the dispensed water/lava to SafeBuckets when dispensed.

I know slide23 was playing around with this a few days ago.

**Comment by ghost** [comment]
If this isn't being done in the morning (~6-8hrs from now) and/or c4's swamped with things, I'll look at this. I had an idea that I half-coded lying around.

**Comment by stevommmm** [comment]
I was doing this by getting the direction the dispenser was facing and adding that block to safebuckets list.

It turns out you can get the liquid to flow before we are able to stop that happening. We trailed a bunch of things but couldn't get it resolved. It appeared that there was a physics update before the event fully finished and we stopped it flowing.

**Comment by ludeman84** [comment]
This is now working through SafeBuckets as of 1.4.2.  Thanks!
