### ISSUE TITLE
Explore TPS performance on P vs. S

### ISSUE THREAD

**Issue by ludeman84** [NerdNu/NerdBugs#32]
As we know, the TPS has consistently been lower on P than on S when the number of users is similar.  We've spent a lot of time trying to figure out what could be responsible, and we've identified three things that seem to have the greatest effect on load:
1. Growth enabled
2. Large number of mobs
3. Large number of protections

C has #3, but not #1 or #2.  S has #1, but not #2 (though the mob count is not _that_ much lower) or #3.  But P has all three.  So, let's do some testing to confirm exactly what is to blame.

Part 1: Data Collection
Set up scripts to log the number of players, TPS, and mob count on S and P every X minutes (X = 5?).  Do this for several days, up to a week.

Part 2: Protection Tests
Temporarily add a huge number of trivial protection regions (e.g. within the spawn area), such that the number of protections on S matches the number on P.  Repeat the testing in Part 1, to see if there is a major difference.

Obviously we can't get rid of growth, but if it turns out protections are a big issue, there are steps that could be taken to try to reduce the number of protections needed.

**Comment by stevommmm** [comment]
Mob / Player counts [already done](https://github.com/NerdNu/KitchenSink/commit/9451ed1004f9cc66deb562fe3637e5e1b95f2394)

Worth noting that Ageable was changed to LivingEntity, which produces the output similiar to:

```
2012-09-20 06:14:57 [INFO] -!- {PIG=21, CREEPER=255, SQUID=88, ENDERMAN=30, MUSHROOM_COW=8, COW=132, IRON_GOLEM=7, VILLAGER=90, SPIDER=66, SKELETON=233, WOLF=1, PLAYER=12, CHICKEN=423, SLIME=29, ZOMBIE=303, SNOWMAN=11, SHEEP=395}
```

In the coming days a protections test will need to be done to S, ideally this would need to happen during peak times ( _sorry playerbase_ ) to give us a real comparison to the kind of TPS issues experienced on P

**Comment by ludeman84** [comment]
These mob/player counts don't seem helpful, it seems like it's only counting mobs in loaded chunks? Or is that all that really matters as far as TPS goes?

Can we log TPS on the same frequency?

**Comment by stevommmm** [comment]
Only loaded chunks has a server impact. We don't care about _totals_, we only care about what is loaded at any given time.

TPS shouldn't be a problem to do

**Comment by totemo** [comment]
I'd like to renew this investigation.  If you have any written records of your findings c45y, I'd appreciate you making them available.

I noticed today in the Seneca iron grinder that the villagers in each pod were breeding out of control, with up to about 20 in each pod.  Multiply that by a total of 3 \* 4 \* 4 pods and that's potentially a lot of villagers, although not all pods had excess villagers.  The middle layer of spawning floors all had on the order of a dozen villagers so that is about (12-4) \* 4 \* 4 = ~128 excess villagers, at least.  Placing floating lava in the corners of each pod seemed to produce a modest tps improvement.

Checking the server logs on P:
grep '\-\!\-' server.log > mobs.txt
cat mobs.txt | while read LINE; do expr match "$LINE" '._VILLAGER=([0-9]_).*'; done | sort -n

Villagers have peaked at 1182 on P, with many many mob counts over the history of the server log showing in excess of 800 at any time.

**Comment by stevommmm** [comment]
I never got to writing something into this to log ticks, from observation pve was 7-10 ticks slower than survival at any given time ( with S hovering around 20 ) 

At the time mobs were very expensive for the server ( likely still are ) so mobs was the most reasonable focal point for squeezing more ticks out of the server

I didn't think to write any of this down at the time, and it has been long enough that my console logging will have rotated ( I only keep 6 months ) so I don't have any data I can call on either

Sorry I can't be of more help

**Comment by tobylane** [comment]
In a similar way to how shearing sheep produces several wool, is it possible for villagers to be powered up in a similar way? Currently iron golems spawn from 10 villagers, could that be reduced?

On the player side I think we should work out a way to stop/cap villager breeding in our builds.

**Comment by totemo** [comment]
Slide did some profiling on P rev 11 prior to the end of the revision and the timings indicated that in fact the LWC onMoveItem() method was a hot spot.  We ran '/lwc admin report' which indicated that there were (60,000) protections, which exceeded the then-configured cache size (50,000).  However, increasing the cache size to 100,000 did not help.

There were large numbers of reads and writes through the cache, despite its increased size. A sampling:

2013-06-14 16:53:59 [INFO]   Usage: 82.89%  ( 41447/50000 )  [ Reads: 285,093,269 <=> 126259.20 r/s ]  [ Writes: 90,075 <=> 39.89 w/s ]
2013-09-27 08:11:36 [INFO]   Usage: 100.00%  ( 50000/50000 )  [ Reads: 1,294,065,813 <=> 186814.76 r/s ]  [ Writes: 107,580 <=> 15.53 w/s ]
2013-09-27 08:16:43 [INFO]   Usage: 60.43%  ( 60433/100000 )  [ Reads: 3,393,684 <=> 102838.91 r/s ]  [ Writes: 121,998 <=> 3696.91 w/s ]
2013-09-27 08:17:26 [INFO]   Usage: 60.43%  ( 60433/100000 )  [ Reads: 10,944,946 <=> 144012.45 r/s ]  [ Writes: 122,034 <=> 1605.71 w/s ]

2013-10-01 04:22:07 [INFO]   Usage: 5.92%  ( 5919/100000 )  [ Reads: 213,546 <=> 594.84 r/s ]  [ Writes: 12,264 <=> 34.16 w/s ]

The last number is after the reset to revision 12.

Those numbers are consistent with LWC bug reports on hoppers (https://github.com/Hidendra/LWC/issues/623).  With the new revision, the LWC performance issue has temporarily abated, but I consider it unresolved until the underlying issue in LWC is fixed.  We retain a PVE 11 test bed for that.

Once the new P revision was under way, with a tick rate less than 5 for 150+ players, we used the rev 11 test bed to investigate Spigot compatibility with our plugin load and subsequently switched to that.  The current performance hot spot is entityTick() in world.  Activation and tracking limits for entities have been reduced, as have spawn limits on mobs (some of these may be able to restored to in-between levels, they were reduced further following an issue with villagers discussed below), and the number of growth chunks has also been decreased.  The hopper checking and transfer periods have also been increased to 20 ticks (from 8).  Credit to gsand for suggesting these tuning changes.  There's some good general discussion of the spawn limits here (http://minecraft.gamepedia.com/Spawn) and here (https://forums.bukkit.org/threads/what-does-spawn-limits-in-bukkit-yml-refer-to.81317/).

Currently, the adaptation I made to the MobLimiter mainly for the zombie AI tracking issue is insufficient to impose a hard cap on villagers because of the propensity of people to move villagers out of the spawning chunk.  An alternative hard cap mechanism is required, which I intend to implement  today.  With large numbers of mobs tightly enclosed, the entityTick() in world can completely dominate the timings and reduce the overall tick rate noticeably for even a relatively small player count, e.g. from 20 down to 13.5 tps for 40 players, 896 villagers in close proximity of each other.  I attribute this to the mob physics calculations.

```
    78.58%   126.61%     317.848 s  63.3037 ms      5.02k   world - entityTick
     6.08%       9.80%    24.597 s  4.8988 ms       5.02k   Player Tick
     2.53%               4.07%    10.229 s  2.0373 ms       5.02k   world - doTickTiles
     2.39%       3.85%     9.661 s  1.9241 ms       5.02k   world - tracker
     2.02%       3.28%     8.156 s  1.6387 ms       4.98k   world - mobSpawn
     1.72%       2.77%     6.948 s  1.3839 ms       5.02k   world - tileEntityTick
     0.81%       0.43%     3.270 s  0.2171 ms      15.06k   entityActivationCheck
```
