### ISSUE TITLE
Make /seen case insensitive

### ISSUE THREAD

**Issue by totemo** [NerdNu/NerdBugs#90]
All other commands are.  Why not /seen?

**Comment by mattman00000** [comment]
er, what does /seen do? if it tells you when the last time someone was on, I believe that commandhelper's functionality for finding when someone was last on is case sensitive, whereas most commands deal with online players, and lowercase can be matched up to the player's name because they're online to be checked for.

**Comment by totemo** [comment]
It's for checking when a player was last seen.  We used to have an alias for "/lb player $name limit 1" and frankly, it worked better.

**Comment by FourDown** [comment]
I would do this, but unfortunately I don't think NerdCH is going to be updated anymore.

@LadyCailin : Could you get more of the CH stuff uploaded when you have a chance?

**Comment by gsand** [comment]
There's a basic example for this on the commandhelper wiki

http://wiki.sk89q.com/wiki/CommandHelper/Staged/API/plast_played
http://wiki.sk89q.com/wiki/CommandHelper/Staged/API/simple_date#Example_8

**Comment by gsand** [comment]
This would have to be fixed through commandhelper, since its handling of this specific feature is case sentitive.

**Comment by totemo** [comment]
Fixed by modification of the existing CH script. Rolled out on P, C, S and event servers.
